require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ArtifactsController do

  # This should return the minimal set of attributes required to create a valid
  # Artifact. As you add validations to Artifact, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ArtifactsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all artifacts as @artifacts" do
      artifact = Artifact.create! valid_attributes
      get :index, {}, valid_session
      assigns(:artifacts).should eq([artifact])
    end
  end

  describe "GET show" do
    it "assigns the requested artifact as @artifact" do
      artifact = Artifact.create! valid_attributes
      get :show, {:id => artifact.to_param}, valid_session
      assigns(:artifact).should eq(artifact)
    end
  end

  describe "GET new" do
    it "assigns a new artifact as @artifact" do
      get :new, {}, valid_session
      assigns(:artifact).should be_a_new(Artifact)
    end
  end

  describe "GET edit" do
    it "assigns the requested artifact as @artifact" do
      artifact = Artifact.create! valid_attributes
      get :edit, {:id => artifact.to_param}, valid_session
      assigns(:artifact).should eq(artifact)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Artifact" do
        expect {
          post :create, {:artifact => valid_attributes}, valid_session
        }.to change(Artifact, :count).by(1)
      end

      it "assigns a newly created artifact as @artifact" do
        post :create, {:artifact => valid_attributes}, valid_session
        assigns(:artifact).should be_a(Artifact)
        assigns(:artifact).should be_persisted
      end

      it "redirects to the created artifact" do
        post :create, {:artifact => valid_attributes}, valid_session
        response.should redirect_to(Artifact.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved artifact as @artifact" do
        # Trigger the behavior that occurs when invalid params are submitted
        Artifact.any_instance.stub(:save).and_return(false)
        post :create, {:artifact => {}}, valid_session
        assigns(:artifact).should be_a_new(Artifact)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Artifact.any_instance.stub(:save).and_return(false)
        post :create, {:artifact => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested artifact" do
        artifact = Artifact.create! valid_attributes
        # Assuming there are no other artifacts in the database, this
        # specifies that the Artifact created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Artifact.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => artifact.to_param, :artifact => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested artifact as @artifact" do
        artifact = Artifact.create! valid_attributes
        put :update, {:id => artifact.to_param, :artifact => valid_attributes}, valid_session
        assigns(:artifact).should eq(artifact)
      end

      it "redirects to the artifact" do
        artifact = Artifact.create! valid_attributes
        put :update, {:id => artifact.to_param, :artifact => valid_attributes}, valid_session
        response.should redirect_to(artifact)
      end
    end

    describe "with invalid params" do
      it "assigns the artifact as @artifact" do
        artifact = Artifact.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Artifact.any_instance.stub(:save).and_return(false)
        put :update, {:id => artifact.to_param, :artifact => {}}, valid_session
        assigns(:artifact).should eq(artifact)
      end

      it "re-renders the 'edit' template" do
        artifact = Artifact.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Artifact.any_instance.stub(:save).and_return(false)
        put :update, {:id => artifact.to_param, :artifact => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested artifact" do
      artifact = Artifact.create! valid_attributes
      expect {
        delete :destroy, {:id => artifact.to_param}, valid_session
      }.to change(Artifact, :count).by(-1)
    end

    it "redirects to the artifacts list" do
      artifact = Artifact.create! valid_attributes
      delete :destroy, {:id => artifact.to_param}, valid_session
      response.should redirect_to(artifacts_url)
    end
  end

end
